# Let's Explore `Numpy` - An Awesome Python Library

**NumPy** - one of the most widely used libraries for numerical computations in Python. It provides support for handling arrays, matrices, and many mathematical functions efficiently.

`Numpy Documentation`
1. Official : 
2. W3School : https://www.w3schools.com/python/numpy/numpy_intro.asp

### 1. **Installing NumPy**
If you haven't installed NumPy yet, you can install it using:
```bash
pip install numpy
```

### 2. **Importing NumPy**
After installing, you can import it with the following convention (alias `np` is common):
```python
import numpy as np
```

### 3. **Key Features of NumPy**
- **N-dimensional array (ndarray)**: NumPy provides the `ndarray` object, which is a powerful n-dimensional array.
- **Broadcasting**: It allows operations on arrays of different shapes.
- **Vectorized operations**: Faster element-wise operations compared to Python lists.
- **Linear algebra**: Provides functions for linear algebra operations, such as dot products, matrix multiplication, etc.
- **Random sampling**: Built-in functions to generate random numbers and distributions.

  Here’s a comparison between **NumPy arrays** and **Python lists**

| **Feature**                | **NumPy Array**                                         | **Python List**                                        |
|----------------------------|--------------------------------------------------------|--------------------------------------------------------|
| **Data Type**               | Homogeneous: All elements must be of the same data type. | Heterogeneous: Can contain elements of different types. |
| **Memory Efficiency**       | More memory efficient due to fixed data type.           | Less memory efficient because of flexible data types.   |
| **Speed**                   | Faster for large datasets due to optimized C-based operations. | Slower for large datasets, as it operates at a higher level. |
| **Mathematical Operations** | Supports element-wise and vectorized operations.        | Requires loops or list comprehensions for element-wise operations. |
| **Multidimensional Data**   | Supports multi-dimensional arrays (2D, 3D, etc.) directly. | Requires nested lists for multi-dimensional data.       |
| **Indexing**                | Advanced indexing and slicing options, including boolean indexing. | Basic indexing and slicing; no advanced features.       |
| **Functionality**           | Extensive mathematical functions and statistical operations available. | Limited to basic Python built-in functions.             |
| **Broadcasting**            | Supports broadcasting, allowing operations on arrays of different shapes. | No broadcasting support. Manual iteration is required for such operations. |
| **Memory Contiguity**       | Uses contiguous blocks of memory for efficient storage. | Elements are stored as references, leading to scattered memory locations. |
| **Flexibility**             | Less flexible in terms of mixed data types.             | More flexible, allows different data types in the same list. |
| **Usage**                   | Primarily used for numerical and scientific computing.   | General-purpose, suitable for various types of data and applications. |
| **Dependencies**            | Requires installation of the NumPy library.             | No external library needed, built into Python.          |
| **Appending/Modifying Elements** | More complex when resizing, as arrays are fixed-size (but NumPy offers resizing functions like `np.append()`). | Easier to modify dynamically, allows appending and removing elements. |
| **Memory Consumption**      | Consumes less memory for large datasets due to contiguous allocation. | Consumes more memory due to dynamic type references. |




### 4. **Creating NumPy Arrays**
You can create NumPy arrays from Python lists or tuples using `np.array()`.

#### Example: Creating arrays
```python
import numpy as np

# 1D array
arr1 = np.array([1, 2, 3, 4])
print(arr1)

# 2D array
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)
```

### 5. **Array Attributes**
Some useful attributes of NumPy arrays include:
- `ndarray.shape`: Gives the dimensions of the array.
- `ndarray.ndim`: Returns the number of dimensions.
- `ndarray.size`: Gives the total number of elements.
- `ndarray.dtype`: Returns the data type of the array.

#### Example:
```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Number of elements:", arr.size)
print("Data type:", arr.dtype)
```

### 6. **Creating Arrays with Predefined Values**
NumPy provides several functions to create arrays with specific values:

- `np.zeros(shape)`: Creates an array filled with zeros.
- `np.ones(shape)`: Creates an array filled with ones.
- `np.eye(n)`: Creates an identity matrix of size `n x n`.
- `np.arange(start, stop, step)`: Returns evenly spaced values within a range.
- `np.linspace(start, stop, num)`: Returns evenly spaced numbers over a specified interval.

#### Example:
```python
# Array of zeros
zeros_arr = np.zeros((2, 3))  # 2 rows, 3 columns
print("Array of zeros:\n", zeros_arr)

# Array of ones
ones_arr = np.ones((2, 2))  # 2x2 matrix
print("Array of ones:\n", ones_arr)

# Identity matrix
identity_matrix = np.eye(3)
print("Identity matrix:\n", identity_matrix)

# Range of values
range_arr = np.arange(0, 10, 2)
print("Range of values:\n", range_arr)

# Evenly spaced numbers
linspace_arr = np.linspace(0, 1, 5)
print("Linspace array:\n", linspace_arr)
```

### 7. **Basic Array Operations**
NumPy arrays support element-wise operations, which means you can perform arithmetic operations directly on arrays.

#### Example:
```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
sum_arr = arr1 + arr2
print("Sum:\n", sum_arr)

# Element-wise multiplication
prod_arr = arr1 * arr2
print("Product:\n", prod_arr)

# Scalar addition
scalar_add = arr1 + 10
print("Scalar addition:\n", scalar_add)
```

### 8. **Indexing and Slicing**
You can access elements of NumPy arrays similar to lists and use slicing to get a sub-array.

#### Example:
```python
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access element at row 1, column 2
print("Element at (1, 2):", arr[1, 2])

# Get a sub-array (slice)
sub_arr = arr[1:, 1:]  # From row 1 onward, column 1 onward
print("Sub-array:\n", sub_arr)
```

### 9. **Reshaping Arrays**
You can reshape arrays using `reshape()`.

#### Example:
```python
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into 2 rows, 3 columns
reshaped_arr = arr.reshape(2, 3)
print("Reshaped array:\n", reshaped_arr)
```

### 10. **Broadcasting**
NumPy automatically handles arrays of different shapes in operations by "broadcasting" them to compatible shapes.

#### Example:
```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Broadcasting a scalar to the entire array
print(arr + 10)
```

### 11. **Random Number Generation**
NumPy’s `random` module allows generating random numbers and arrays.

#### Example:
```python
# Random numbers between 0 and 1
rand_arr = np.random.rand(3, 3)  # 3x3 matrix of random values
print("Random array:\n", rand_arr)

# Random integers
rand_ints = np.random.randint(1, 10, size=(2, 3))  # 2x3 matrix of random ints between 1 and 9
print("Random integers:\n", rand_ints)
```

### 12. **Linear Algebra**
NumPy provides useful linear algebra functions like `dot()`, `transpose()`, etc.

#### Example:
```python
# Dot product of two arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

dot_product = np.dot(arr1, arr2)
print("Dot product:\n", dot_product)
```

---


# Practice and Special Notes

In [2]:
import numpy as np
import sys

In [3]:
a = np.array([1,2,3])
b = np.array([[4,5,6],[7,8,9]])
c = np.array([10.2,56.5,87.1], dtype = 'int64') #1D
m = np.array([[1,2,3,4,5,6,7,8,9],[9,8,7,6,5,4,3,2,1]]) #2D
n = np.array([[[4,5,6],[7,8,9]], [[10,11,12],[13,14,16]],[[21,22,23],[41,45,48]]]) #3D

In [4]:
# Dimantion
print(a.ndim)
print(b.ndim)

1
2


In [5]:
# Get shape
b.shape

(2, 3)

In [6]:
# get type

b.dtype

dtype('int32')

In [7]:
# item size
a.itemsize

4

In [8]:
# total size
a.nbytes

12

In [9]:
c.nbytes

24

In [10]:
m

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5, 4, 3, 2, 1]])

In [11]:
# specific element name[r,c] expl : 8 of 2nd list
m[1,1]

8

In [12]:
# row - 2nd list
m[1 , :]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [13]:
# col - 3,7
m[:, 2]

array([3, 7])

In [14]:
m

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [9, 8, 7, 6, 5, 4, 3, 2, 1]])

In [15]:
# row slicing 3 to 7
m[0, 2:7:1]

array([3, 4, 5, 6, 7])

In [16]:
# change value
m[1,0] = 99
m

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [99,  8,  7,  6,  5,  4,  3,  2,  1]])

In [17]:
# change column
m[:, 1] = 5
m[:, 2] = [34,43]
m

array([[ 1,  5, 34,  4,  5,  6,  7,  8,  9],
       [99,  5, 43,  6,  5,  4,  3,  2,  1]])

In [18]:
# 3D array
n

array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 16]],

       [[21, 22, 23],
        [41, 45, 48]]])

In [19]:
n[:,1,:]
# : means all of them
# [big row, small row, col]

array([[ 7,  8,  9],
       [13, 14, 16],
       [41, 45, 48]])

In [20]:
n[:1,1,1:]

array([[8, 9]])

`Automatic Value Fill`

In [21]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones([2,2,2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [23]:
np.full([3,3],69)

array([[69, 69, 69],
       [69, 69, 69],
       [69, 69, 69]])

In [24]:
np.random.randint(1,10,size=[3,3,3])

array([[[8, 3, 6],
        [8, 6, 9],
        [3, 1, 2]],

       [[7, 5, 8],
        [7, 6, 9],
        [6, 7, 6]],

       [[4, 9, 4],
        [7, 5, 8],
        [3, 9, 3]]])

In [25]:
arr = np.array(
      [[[4, 9, 4],
        [7, 2, 8],
        [6, 8, 8]],

       [[8, 5, 3],
        [5, 6, 7],
        [3, 7, 3]],

       [[1, 8, 8],
        [2, 8, 1],
        [8, 7, 3]]])

In [26]:
np.random.rand(3,3)

array([[0.94456517, 0.98460144, 0.81042711],
       [0.01033147, 0.44917858, 0.7959147 ],
       [0.39845228, 0.05454689, 0.20976765]])

In [27]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# array repeat process - axis0 means row 1 means col
# use 2 dimenstion to repeat the entire row or col instead of repeating value
arr = np.array([[1,2,3]])
arr.repeat(3,axis = 0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [47]:
# change a bigger amount of array from another array

arr = np.ones([5,5])
arr2 = np.zeros([3,3])
print(arr,arr2,sep = "\n\n", end = "\n\n")

arr[1:4,1:4] = arr2
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [50]:
# try this with random numbers with fancy style

arr = np.random.randint(1,10,size = [7,7])
arr[1:6,1:6] = np.zeros([5,5])
arr

array([[4, 6, 9, 3, 1, 8, 7],
       [8, 0, 0, 0, 0, 0, 3],
       [7, 0, 0, 0, 0, 0, 4],
       [9, 0, 0, 0, 0, 0, 6],
       [2, 0, 0, 0, 0, 0, 3],
       [7, 0, 0, 0, 0, 0, 4],
       [5, 2, 4, 4, 6, 4, 5]])

In [54]:
# array points the same object with different name so copying array is a careful task

a = np.array([1,3])
b = a
b[0] = 700
print(a)
print(b)

# to change this problem use copy() method
print("Second Method")
b = a.copy()
b[0] = 50
print(a)
print(b)

[700   3]
[700   3]
Second Method
[700   3]
[50  3]


# Math with Numpy

In [55]:
# numpy calculate with individual elements all time

In [57]:
a = np.full([3,3],4)
b = np.random.randint(1,9,size = [3,3])
print(a)
print(b)

[[4 4 4]
 [4 4 4]
 [4 4 4]]
[[1 3 8]
 [6 8 7]
 [7 8 5]]


In [58]:
a + b

array([[ 5,  7, 12],
       [10, 12, 11],
       [11, 12,  9]])

In [60]:
a ** b

array([[    4,    64, 65536],
       [ 4096, 65536, 16384],
       [16384, 65536,  1024]])

In [59]:
a * b
# this is not matrix mulptiplication.

array([[ 4, 12, 32],
       [24, 32, 28],
       [28, 32, 20]])

In [62]:
# for matrix multiplication
c = np.matmul(a,b)
c

array([[56, 76, 80],
       [56, 76, 80],
       [56, 76, 80]])

In [65]:
# find the determiner
np.linalg.det(b)

-23.00000000000001